export const Question = [
    {
        prompt: "What year was dev Ismail was born?",
        optionA: "1999",
        optionB: "2000",
        optionC: "2007",
        optionD: "2023",
        answer: "C"
    },
    {
        prompt: "How many two can we see in ten?",
        optionA: "2",
        optionB: "5",
        optionC: "1",
        optionD: "8",
        answer: "B",
    },
    {
        prompt: "Which year did Nigeria gain independence?",
        optionA: "1999",
        optionB: "2000",
        optionC: "1960",
        optionD: "2023",
        answer: "C",
    },
    {
        prompt: "What is the closest star to earth?",
        optionA: "moon",
        optionB: "sun",
        optionC: "mars",
        optionD: "mass",
        answer: "B",
    },
     {
         prompt: "in which country was the titanic built?",
         optionA: "United Kingdom",
         optionB: "France",
         optionC: "United States",
         optionD: "Nigeria",
         answer: "A",
     },
     {
         prompt: "How old is the earth?",
         optionA: "254 million years old",
         optionB: "4.5 billion years old",
         optionC: "13.5 billion years old",
         optionD: "17 million years old",
         answer: "B",
     },
     {
         prompt: "Who is considered the father of geometry?",
         optionA: "Aristotle",
         optionB: "Euclid",
         optionC: "Pythagoras",
         optionD: "Ismail",
         answer: "B",
     },
     {
         prompt: "What is the capital of south Korea?",
         optionA: "Kyoto",
         optionB: "Bangkok",
         optionC: "seoul",
         optionD: "damm",
         answer: "C",
     },
     {
         prompt: "In which country is the city of Venice located?",
         optionA: "Austria",
         optionB: "Switzerland",
         optionC: "italy",
         optionD: "spain",
         answer: "C",
     },
     {
         prompt: "How many muscles control the movement of the human eye?",
         optionA: "6",
         optionB: "12",
         optionC: "32",
         optionD: "17",
         answer: "A",
     },
{
         prompt: "What is the capital of the united states",
         optionA: "Los Angeles",
         optionB: "New York",
         optionC: "Washington D.C.",
         optionD: "santo",
         answer: "C",
     },
{
         prompt: "The shark is the most Dangerous animal to humans",
         optionA: "true",
         optionB: "false",
         optionC: "both",
         optionD: "all of the above",
         answer: "B",
     },
{
         prompt: "In which continent is panama located?",
         optionA: "Europe",
         optionB: "Asia",
         optionC: "America",
         optionD: "Nigeria",
         answer: "C",
     },
{
         prompt: "Where can we find the animal called Beluga?",
         optionA: "Land",
         optionB: "Water",
         optionC: "Air",
         optionD: "House",
         answer: "B",
     }, {
         prompt: "How long did the 'Hundred Years' War last?",
         optionA: "64 years",
         optionB: "100 years",
         optionC: "166 years",
         optionD: "29 years",
         answer: "C",
     },
{
    prompt: "Which year did Nigeria gain independence?",
        optionA: "1999",
        optionB: "2000",
        optionC: "1960",
        optionD: "2023",
        answer: "C",
      }
 ]